/*
 * generated by Xtext
 */
package de.wwu.md2.framework;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TestRuntimeModule extends de.wwu.md2.framework.AbstractTestRuntimeModule {

}
