/*
 * generated by Xtext
 */
package de.wwu.md2.framework.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TestUiModule extends de.wwu.md2.framework.ui.AbstractTestUiModule {
	public TestUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
