/*
 * generated by Xtext
 */
package de.wwu.md2.framework.ui.contentassist;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
public class TestProposalProvider extends de.wwu.md2.framework.ui.contentassist.AbstractTestProposalProvider {

}
